In [2]:
import numpy as np

In [3]:
np.__version__

'1.26.4'

In [ ]:
#Create a numpy array
arr=np.array([1,2,3,4,5]) #[1,2,3,4,5] = list
print(arr)

[1 2 3 4 5]


In [ ]:
# Create Array from python list (1D)
arr1 = np.array([1,2,3,4,5])
print(arr1)

[1 2 3 4 5]


In [10]:
#create a 2D array (Matrix)
arr2=np.array([[1,2,5],
              [3,4,6]])
print(arr2)

[[1 2 5]
 [3 4 6]]


In [ ]:
#create 3D array
arr3 = np.array([
    [[1, 2] , [3, 4]],
    [[5, 6] , [7, 8]]
])
print(arr3)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [13]:
# Create array with range(arange)

arr4=np.arange(1,10)
print(arr4)

[1 2 3 4 5 6 7 8 9]


In [ ]:
# zeros Array

zero_array= np.zeros((3,4))  # 3 x 4 matrix of zeros; #3 rows with 4 element as zero
print(zero_array) 

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [ ]:
#ones array
ones_array=np.ones((2,3))
print(ones_array)

[[1. 1. 1.]
 [1. 1. 1.]]


In [ ]:
#Full array (Custom array)
full_arr=np.full((3,3), 7)  # 3 x 3 matrix with 7 as a custom number
print(full_arr)

[[7 7 7]
 [7 7 7]
 [7 7 7]]


In [ ]:
#Identity Matrix (eye)

eye_arr = np.eye(4)
print(eye_arr)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [ ]:
#Data type
arr_float = np.array([1,2,3], dtype=int) #Forces array type to int,float, etc
print(arr_float)

[1 2 3]


In [ ]:
arr = np.array([[1,2,3],
                [4,5,6]])
print(arr.shape) #means 2 rows and 3 columns

(2, 3)
