In [2]:
import numpy as np

In [3]:
np.__version__

'1.26.4'

In [ ]:
#Create a numpy array
arr=np.array([1,2,3,4,5]) #[1,2,3,4,5] = list
print(arr)

[1 2 3 4 5]


In [ ]:
# Create Array from python list (1D)
arr1 = np.array([1,2,3,4,5])
print(arr1)

[1 2 3 4 5]


In [10]:
#create a 2D array (Matrix)
arr2=np.array([[1,2,5],
              [3,4,6]])
print(arr2)

[[1 2 5]
 [3 4 6]]


In [ ]:
#create 3D array
arr3 = np.array([
    [[1, 2] , [3, 4]],
    [[5, 6] , [7, 8]]
])
print(arr3)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [13]:
# Create array with range(arange)

arr4=np.arange(1,10)
print(arr4)

[1 2 3 4 5 6 7 8 9]


In [ ]:
# zeros Array

zero_array= np.zeros((3,4))  # 3 x 4 matrix of zeros; #3 rows with 4 element as zero
print(zero_array) 

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [ ]:
#ones array
ones_array=np.ones((2,3))
print(ones_array)

[[1. 1. 1.]
 [1. 1. 1.]]


In [ ]:
#Full array (Custom array)
full_arr=np.full((3,3), 7)  # 3 x 3 matrix with 7 as a custom number
print(full_arr)

[[7 7 7]
 [7 7 7]
 [7 7 7]]


In [ ]:
#Identity Matrix (eye)

eye_arr = np.eye(4)
print(eye_arr)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [ ]:
#Data type
arr_float = np.array([1,2,3], dtype=int) #Forces array type to int,float, etc
print(arr_float)

[1 2 3]


In [ ]:
#Shape (Rows, Columns)
arr = np.array([[1,2,3],
                [4,5,6]])
print(arr.shape) #means 2 rows and 3 columns

(2, 3)


In [ ]:
# Size (Total Elements)
print(arr.size) #Counts total number of elements in an array

6


In [ ]:
# Number of Dimensions
print(arr.ndim) #Gives Dimension of array 1D,2D,3D,etc 

2


In [ ]:
#Reshape Array
new_arr = arr.reshape(3,2)
print(new_arr) # We transpose the matrix

[[1 2]
 [3 4]
 [5 6]]


In [25]:
#Flatten (Convert to 1D)

flat = arr.flatten()
print(flat)

[1 2 3 4 5 6]


In [28]:
#Indexing in 1D array

arr = np.array([10,20,30,40,50])
print(arr[0]) #first element
print(arr[2]) #third element
print(arr[-1]) #last element

10
30
50


In [29]:
#Slicing in 1D array
print(arr[1:4])

[20 30 40]


In [ ]:
#Indexing in 2D Array (Row, Column)
matrix = np.array([[1, 2, 3],  #[a00 , a01, a02]
                   [4, 5, 6],  #[a10 , a11, a12]
                   [7, 8, 9]]) #[a20 , a21, a22]
print(matrix[2, 2])

9


In [ ]:
# Getting Full row

print(matrix[1])  #Returns second row

[4 5 6]


In [ ]:
#Getting Full columns
print(matrix[:, 2])  #':' means all rows, 2 means third column 

[3 6 9]


In [ ]:
#slicing Rows and Columns
print(matrix[0:2 , 1:3]) #Rows 0 to 1; Columns 1 to 2

[[2 3]
 [5 6]]


In [ ]:
#Boolean Indexing
arr2=np.array([5,10,15,20,25])
print(arr2[arr2>15]) #Returns values greater than 15

[20 25]
